=== athlon128/AppStore/scripts/sidestore-source.schema.json
{
  "$ref": "#/definitions/Source",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "App": {
      "additionalProperties": false,
      "properties": {
        "beta": {
          "description": "Here you can specify whether apps should be classified as a beta application and receive a special beta tag on its app listing.\n\nCurrently, this is also tied in with the Patreon app locking system used with AltStore/Delta betas. But it is not recommended to attempt to use it for this purpose since it will ultimately be changing in the future.",
          "type": "boolean"
        },
        "bundleIdentifier": {
          "description": "SideStore uses this to separate apps as individual listings.\n\nThis must be the same as your application's `CFBundleIdentifier` (located in Info.plist) in order for SideStore to be able to open the app after installation. Technically, it can be any unique string, but for all SideStore functionality to work, it should be the same as the application.",
          "type": "string"
        },
        "developerName": {
          "description": "Also self-explanatory, this is just the name of the developer/developers that will appear in the SideStore app listing.",
          "type": "string"
        },
        "downloadURL": {
          "deprecated": "Please use the {@link versions } property, this is just for backwards compatibility",
          "description": "This should point directly to wherever your IPA is hosted.\n\nIf you are planning on releasing your app in the future, this property is still required but it doesn't have to actually point to a valid file.",
          "type": "string"
        },
        "iconURL": {
          "description": "This should point directly to wherever you host the icon for your app. Note that this doesn't have to be the same as the icon used for the actual application, but it is recommended to maintain consistency.",
          "type": "string"
        },
        "localizedDescription": {
          "description": "This is where you can include every feature and detail about your app. The user will see the first 5 lines of text then they can click \"More\" to expand to the full section. So you should think of the first couple sentences as a quick pitch for your app.",
          "type": "string"
        },
        "name": {
          "description": "Rather self-explanatory, this is the name of your app as it should appear in the SideStore.",
          "type": "string"
        },
        "permissions": {
          "description": "This is to show the user what various permissions your app requires. Create an entry for each separate permission your app requires.\n\nIt is *highly* recommended to include these permissions if your app uses them as this disclosure provides additional trust with the user.",
          "items": {
            "$ref": "#/definitions/Permission"
          },
          "type": "array"
        },
        "screenshotURLs": {
          "description": "These should point directly to any number of screenshots/images that display your app's functionality. The first two will be displayed under the app listing in the browse tab, and the rest will be visible on the app's page.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "size": {
          "deprecated": "Please use the {@link versions } property, this is just for backwards compatibility",
          "description": "This is an integer value that should be set equivalent to the size of your IPA in bytes. This gives the user an idea of how large the application is before they install.",
          "type": "number"
        },
        "subtitle": {
          "description": "This should be a very short description of your app that will appear in the browse tab of SideStore. It should give a quick one sentence explanation of your app and why a user wants it. The most effective subtitles tend to around 6-10 words long.",
          "type": "string"
        },
        "tintColor": {
          "description": "This might take some experimentation, but the best tint color is usually choosing one of the darker colors represented in your app icon. The tint color will be used in two places:\n\n- For the install button\n- As a background color for the larger app listing bubble (but this will be a lighter shade)\n\nThe tint color must be in the 6 character Hex format, with the '#' before the 6 characters as optional.",
          "type": "string"
        },
        "version": {
          "deprecated": "Please use the {@link versions } property, this is just for backwards compatibility",
          "description": "This must match your application's `CFBundleShortVersionString` (located in Info.plist) in order for SideStore updates to work properly.",
          "type": "string"
        },
        "versionDate": {
          "deprecated": "Please use the {@link versions } property, this is just for backwards compatibility",
          "description": "This should be the date that you are releasing your application, and should be written in the format `YYYY-MM-DD` (other formats standard formats will work as well, but this is the only info required and shown to the user).\n\nIf you are planning on releasing your application in the future, after everyone has installed your source, there is an additional format available: `YYYY-MM-DDTHH:MM:SS`\n\nUsing this format will create an automatic timer countdown to the release time specified. Please note that the time is automatically assumed to be UTC and uses a 24 hour clock.\n\nIf you would rather use the time in your timezone, add `-08:00` to the end of the date, where that `-08` corresponds to the number of hours difference between UTC and your timezone. It is also important to note that UTC does not change with daylight saving time, so be careful if you are releasing around that time of year as it can be easy to miscalculate.",
          "type": "string"
        },
        "versionDescription": {
          "deprecated": "Please use the {@link versions } property, this is just for backwards compatibility",
          "description": "Use this to tell the user what new features you introduced or what bugs you squashed with the latest version.",
          "type": "string"
        },
        "versions": {
          "description": "A list containing the version(s) of your application. New with AltSource v2.0 API.\n\nImportant note: SideStore will display the first version (with compatible min/max iOS versions) in the list as the \"latest\" release, regardless of version or date. So keep in mind that the order that versions appear must be in reverse chronological order.",
          "items": {
            "$ref": "#/definitions/Version"
          },
          "type": "array"
        }
      },
      "required": [
        "name",
        "bundleIdentifier",
        "developerName",
        "localizedDescription",
        "iconURL",
        "versions"
      ],
      "type": "object"
    },
    "News": {
      "additionalProperties": false,
      "properties": {
        "appID": {
          "description": "This must be an exact match to the `bundleIdentifier` of the app listing in order for it to work properly.\n\nThis is required if you want an app listing to appear below the news item for quick installation.\n\nIt also makes it so that when a user click on the news item, it will take them to the specified app's page. This will be overridden if a url is also specified.",
          "type": "string"
        },
        "caption": {
          "description": "Similar to the caption for your app listing, this should be about a sentence. While there is technically no limit to the caption size, no one wants a giant text blob in their news feed.\n\nIf there is more to your news than a couple sentences can deliver, try using an image or link to a website.",
          "type": "string"
        },
        "date": {
          "description": "This date should follow the same format as  {@link  Version.date  }  for app listings: `YYYY-MM-DD`.\n\nPlease note that the date does not currently display on any news items and neither does the time (if provided). Instead, it is required for SideStore to organize the news into chronological order.",
          "type": "string"
        },
        "identifier": {
          "description": "This must be a unique identifier that should not be used by any other news items in SideStore.",
          "type": "string"
        },
        "imageURL": {
          "description": "This should be a direct link to any image you want to feature on your news item. The recommended size for this image is 960x540 or any image with a 16:9 aspect ratio. SideStore will also take whatever image you provide it with, then crop and center it to the correct aspect ratio. Be careful not to put any important information in the corners since the SideStore rounds the images corners by default.",
          "type": "string"
        },
        "notify": {
          "description": "When set to true, SideStore will send all users of the source a notification with the title of the news item.\n\nNote that the notification will not be instantaneous: it will occur whenever SideStore attempts a background refresh (the same time that update notifications occur) and it does require users to leave SideStore running in the background.",
          "type": "boolean"
        },
        "tintColor": {
          "description": "This has the same function as  {@link  App.tintColor  } . The only difference is that now it will be used as the background color for your news item. Keep in mind that it does not apply to the app listing if you supplied an  {@link  appID } . The app listing that appears below the news article will use the tintColor specific to that app.",
          "type": "string"
        },
        "title": {
          "description": "Fairly straightforward, this will be the headline for your news item.",
          "type": "string"
        },
        "url": {
          "description": "This should be used to link users to a website when they click the news item. The link will open in SideStore's built-in web browser (based off safari).",
          "type": "string"
        }
      },
      "required": [
        "title",
        "identifier",
        "caption",
        "date"
      ],
      "type": "object"
    },
    "Permission": {
      "additionalProperties": false,
      "properties": {
        "type": {
          "$ref": "#/definitions/PermissionType",
          "description": "The accepted permission types are the following:\n\n- photos\n- camera\n- location\n- contacts\n- reminders\n- music\n- microphone\n- speech-recognition\n- background-audio\n- background-fetch\n- bluetooth\n- network\n- calendars\n- faceid\n- siri\n- motion"
        },
        "usageDescription": {
          "description": "This should explain what the permission is and why your app needs it.",
          "type": "string"
        }
      },
      "required": [
        "type",
        "usageDescription"
      ],
      "type": "object"
    },
    "PermissionType": {
      "enum": [
        "photos",
        "camera",
        "location",
        "contacts",
        "reminders",
        "music",
        "microphone",
        "speech-recognition",
        "background-audio",
        "background-fetch",
        "bluetooth",
        "network",
        "calendars",
        "faceid",
        "siri",
        "motion"
      ],
      "type": "string"
    },
    "Source": {
      "additionalProperties": false,
      "description": "Web docs available at https://sidestore.io/sidestore-source-types\n\nBased on https://github.com/SideStore/SideStore-Docs/blob/main/references/sources.md",
      "properties": {
        "apps": {
          "items": {
            "$ref": "#/definitions/App"
          },
          "type": "array"
        },
        "identifier": {
          "description": "This is a bundle identifier SideStore uses to keep your source separate from every other source. For this reason, it is recommended to follow Apple's standard for an identifier.\n\nIt's important to note here that changing this identifier down the road will have **consequences**. Users with the source already installed will suddenly have conflicting identifiers with the online source and will cause an error in SideStore that will require them to completely remove the source before they can add it back.",
          "type": "string"
        },
        "name": {
          "description": "The name of your source. This will appear in SideStore.",
          "type": "string"
        },
        "news": {
          "items": {
            "$ref": "#/definitions/News"
          },
          "type": "array"
        },
        "sourceURL": {
          "description": "If your user adds your Source using a URL shortener or you have the link to file stored on CDN, it is recommended that you include this property. This allows SideStore to save the exact link to the file which speeds up retrieval time.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "identifier",
        "apps"
      ],
      "type": "object"
    },
    "Version": {
      "additionalProperties": false,
      "properties": {
        "date": {
          "description": "This should be the date that you are releasing your application, and should be written in the format `YYYY-MM-DD` (other formats standard formats will work as well, but this is the only info required and shown to the user).\n\nIf you are planning on releasing your application in the future, after everyone has installed your source, there is an additional format available: `YYYY-MM-DDTHH:MM:SS`\n\nUsing this format will create an automatic timer countdown to the release time specified. Please note that the time is automatically assumed to be UTC and uses a 24 hour clock.\n\nIf you would rather use the time in your timezone, add `-08:00` to the end of the date, where that `-08` corresponds to the number of hours difference between UTC and your timezone. It is also important to note that UTC does not change with daylight saving time, so be careful if you are releasing around that time of year as it can be easy to miscalculate.",
          "type": "string"
        },
        "downloadURL": {
          "description": "This should point directly to wherever your IPA is hosted.\n\nIf you are planning on releasing your app in the future, this property is still required but it doesn't have to actually point to a valid file.",
          "type": "string"
        },
        "localizedDescription": {
          "description": "Use this to tell the user what new features you introduced or what bugs you squashed with the latest version.",
          "type": "string"
        },
        "maxOSVersion": {
          "description": "These are used to indicate the iOS version restrictions that your app may have (inclusively). It also allows you to support multiple different versions of your app that can support different iOS version ranges.",
          "type": "string"
        },
        "minOSVersion": {
          "description": "These are used to indicate the iOS version restrictions that your app may have (inclusively). It also allows you to support multiple different versions of your app that can support different iOS version ranges.",
          "type": "string"
        },
        "size": {
          "description": "This is an integer value that should be set equivalent to the size of your IPA in bytes. This gives the user an idea of how large the application is before they install.",
          "type": "number"
        },
        "version": {
          "description": "This must match your application's `CFBundleShortVersionString` (located in Info.plist) in order for SideStore updates to work properly.",
          "type": "string"
        }
      },
      "required": [
        "version",
        "date",
        "downloadURL",
        "size"
      ],
      "type": "object"
    }
  }
}

=== athlon128/AppStore/source.json
{
  "name": "My Private Apps",
  "identifier": "com.athlon128.appstore",
  "sourceURL": "https://athlon128.github.io/AppStore/source.json",
  "apps": [
    {
      "name": "Fluvo 流序",
      "bundleIdentifier": "com.streamcatch.app",
      "developerName": "athlon128",
      "localizedDescription": "Fluvo（流序）是一款原生 iOS 视频与图集下载器，支持 MP4/HLS、抖音与 X/Twitter 公开媒体解析、媒体库管理和系统分享链接导入。具体兼容范围以应用说明为准。",
      "iconURL": "https://athlon128.github.io/AppStore/icons/Fluvo.png",
      "versions": [
        {
          "version": "0.1.0",
          "date": "2026-10-28T08:16:38Z",
          "localizedDescription": "Fluvo 流序 0.1.0（构建 11）\n\n- 使用 2026-10-28 当前开发工作区重新生成 iPhoneOS / arm64 Release IPA，最低 iOS 17.0。\n- 包含精简首页和 FluvoShare 系统分享扩展：接收 URL 或分享文案，保存后手动回到 Fluvo 导入解析；MP4/M3U8 下载仍需确认。\n- 保留 X/Twitter 视频与图集、网页备用解析及网站登录会话、抖音视频与图集、MP4/HLS、后台 AES-128、媒体库与批量删除功能。\n- 本次重新运行 66 项核心测试全部通过；Release Archive、ZIP CRC、arm64/iOS 平台、两个 bundle 的版本与 App Group、ad-hoc 签名验证通过。\n\n这是供 SideStore 重签名的 IPA：本机没有开发者签名证书，包内为 ad-hoc 签名，没有开发者描述文件，不能直接点击安装。通过 SideStore 使用自己的 Apple 账号重签名后安装。包内含一个分享扩展；安装时保留扩展才能使用系统分享。\n\n主 App：com.streamcatch.app；扩展：com.streamcatch.app.share；原始 App Group：group.com.streamcatch.app。SideStore/签名工具可能重映射 Bundle ID 和 App Group；主 App、扩展的权限及 FluvoAppGroup 配置必须指向同一实际 Group。此次未进行 iPhone 安装或真实签名后分享验收，不能以构建成功代表这些操作已通过。\n\nIPA 字节数：5867002\nSHA-256：c4ac764673e65feacdc0ffd73f29f97725b2c4f625e3e5139f3b26df8065c38b\n\n本 Release 的 Git Tag 指向独立发布仓库；应用开发源码未上传到此仓库。\n",
          "downloadURL": "https://github.com/athlon128/AppStore/releases/download/com.streamcatch.app-v0.1.0-b11/com.streamcatch.app-0.1.0-11.ipa",
          "size": 5867002,
          "minOSVersion": "17.0"
        }
      ]
    }
  ],
  "news": []
}
